/*Задание 1*/
CREATE TABLE t_caterer(
  ID_caterer INT NOT NULL ENABLE,
  NAME NVARCHAR(50) NOT NULL ENABLE,
  ADDRESS NVARCHAR(100) NOT NULL ENABLE,
  PHONE NVARCHAR(20) NOT NULL ENABLE,
  FAX NVARCHAR(20) NOT NULL ENABLE,
  CONSTRAINT PK_caterer PRIMARY KEY (ID_caterer) ENABLE);

CREATE TABLE t_Store(
  ID_Store INT NOT NULL ENABLE,
  NAME NVARCHAR(20) NOT NULL ENABLE,
  CONSTRAINT PK_Store PRIMARY KEY (ID_Store) ENABLE);

CREATE TABLE t_Material(
  ID_Material INT NOT NULL ENABLE,
  NAME VARCHAR2(100) NOT NULL ENABLE,
  ID_Messure INT NOT NULL ENABLE,
  CONSTRAINT PK_Material PRIMARY KEY (ID_Material) ENABLE,
  CONSTRAINT FK_Material_Messure 
    FOREIGN KEY (ID_Messure) REFERENCES 
    t_Messure (ID_Messure) ENABLE);

CREATE TABLE t_Messure(
  ID_Messure INT NOT NULL ENABLE,
  NAME VARCHAR2(5) NOT NULL ENABLE,
  CONSTRAINT PK_Messure PRIMARY KEY (ID_Messure) ENABLE);

CREATE TABLE t_Supply(
  ID_Supply INT NOT NULL ENABLE,
  ID_caterer INT NOT NULL ENABLE,
  ID_Material INT NOT NULL ENABLE,
  ID_Store INT NOT NULL ENABLE,
  Supply_Date DATE NOT NULL ENABLE,
  VOLUME INT NOT NULL ENABLE,
  CONSTRAINT PK_Supply PRIMARY KEY (ID_Supply) ENABLE,
  CONSTRAINT FK_Supply_caterer
    FOREIGN KEY (ID_caterer) REFERENCES
    t_caterer (ID_caterer) ENABLE,
  CONSTRAINT FK_Supply_Material
    FOREIGN KEY (ID_Material) REFERENCES
    t_Material (ID_Material) ENABLE,
  CONSTRAINT FK_Supply_Store
    FOREIGN KEY (ID_Store) REFERENCES
    t_Store (ID_Store) ENABLE);

CREATE TABLE t_Surplus(
  ID_Surplus INT NOT NULL ENABLE
  ID_Material INT NOT NULL ENABLE,
  ID_Store INT NOT NULL ENABLE,
  VOLUME INT CHECK (VOLUME>=0) ENABLE,
  CONSTRAINT PK_Surplus PRIMARY KEY (ID_Surplus) ENABLE,
  CONSTRAINT FK_Surplus_Material
    FOREIGN KEY (ID_Material) REFERENCES
    t_Material (ID_Material) ON DELETE CASCADE,
  CONSTRAINT FK_Surplus_Store
    FOREIGN KEY (ID_Store) REFERENCES
    t_Store (ID_Store) ON DELETE CASCADE);

CREATE TABLE t_Deliver(
  ID_Deliver INT NOT NULL ENABLE,
  ID_Section INT NOT NULL ENABLE,
  ID_Material INT NOT NULL ENABLE,
  ID_Store INT NOT NULL ENABLE,
  Deliver_DATE DATE NOT NULL ENABLE,
  CONSTRAINT PK_Deliver PRIMARY KEY (ID_Deliver) ENABLE,
  CONSTRAINT FK_Deliver_Section
    FOREIGN KEY (ID_Section) REFERENCES
    t_Section (ID_Section) ON DELETE CASCADE,
  CONSTRAINT FK_Deliver_Material
    FOREIGN KEY (ID_Material) REFERENCES
    t_Material (ID_Material) ON DELETE CASCADE,
  CONSTRAINT FK_Deliver_Srore
    FOREIGN KEY (ID_Store) REFERENCES
    t_Store (ID_Store) ON DELETE CASCADE);

CREATE TABLE t_inprice(
  ID_inprice INT NOT NULl ENABLE,
  ID_Material INT NOT NULL ENABLE,
  PRICE_DATE DATE NOT NULL ENABLE,
  PRICE NUMBER(10,2) CHECK (PRICE>=0) ENABLE,
  CONSTRAINT FK_inprice_Material 
    FOREIGN KEY (ID_Material) REFERENCES
    t_Material (ID_Material)
    ON DELETE CASCADE);
    
CREATE TABLE t_Section(
  ID_Section INT NOT NULL ENABLE,
  NAME NVARCHAR(50) NOT NULL ENABLE,
  ID_Employer INT NOT NULL ENABLE,
  CONSTRAINT PK_Section PRIMARY KEY (ID_Section) ENABLE,
  CONSTRAINT FK_Section_Employer
    FOREIGN KEY (ID_Employer) REFERENCES
    t_Employer (ID_Employer) ON DELETE CASCADE);

CREATE TABLE t_Employer(
  ID_Employer INT NOT NULL ENABLE,
  SURNAME NVARCHAR(20) NOT NULL ENABLE,
  NAME NVARCHAR(20) NOT NULL ENABLE,
  FATHERNAME NVARCHAR(20) NOT NULL ENABLE,
  CONSTRAINT PK_Employer PRIMARY KEY (ID_Employer) ENABLE);

/**/
ALTER TABLE t_Employer
	ADD SEX CHAR(1) DEFAULT 'M' CHECK(SEX IN ('M', 'W'))
	ADD BIRTHDATE DATE 
	ADD MARRIAGE VARCHAR2(10);

CREATE TABLE t_JOB(
	ID_JOB INT NOT NULL,
	NAME VARCHAR(30),
	CONSTRAINT PK_JOB PRIMARY KEY (ID_JOB));

ALTER TABLE t_Employer
	ADD ID_JOB INT
	ADD CONSTRAINT FK_Employer
	  FOREIGN KEY (ID_JOB) REFERENCES
	  t_JOB (ID_JOB) ON DELETE SET NULL);

/*Задание 2*/
ALTER TABLE t_caterer
  DROP COLUMN ADDRESS;
 ALTER TABLE t_caterer
   ADD (Legal_Address NVARCHAR(100) NOT NULL,
   	  Actual_Address NVARCHAR(100) NOT NULL,
   	  E_Mail NVARCHAR(50));

 /*Задание 3*/
 ALTER TABLE t_inprice
   ADD CONSTRAINT PK_inprice
     PRIMARY KEY (ID_Material, PRICE_DATE));

/*Задание 4*/
CREATE TABLE t_Group(
  ID_Group INT NOT NULL ENABLE,
  NAME NVARCHAR(40) NOT NULL ENABLE,
  CONSTRAINT PK_Group
    PRIMARY KEY (ID_Group));

 ALTER TABLE t_Material
   ADD ID_Group INT
   ADD CONSTRAINT FK_Material_Group
       FOREIGN KEY (ID_Group) REFERENCES
       t_Group (ID_Group) ON DELETE SET NULL;

/*Задание 5*/
ALTER TABLE t_Supply
  MODIFY (VOLUME INT CHECK (VOLUME>=0)).